spring.application.name=beusu
server.port=8083
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/tysweb2627usuarios?serverTimezone=Europe/Madrid&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=tysweb2025
spring.datasource.password=tysweb2025
beusu.token.minutos-caducidad=60